version: '3'

services:
  app:
    build: .
    container_name: English-Management-system
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://kxck:d7NWu9Ulrm6EfpTi@englishcenter.rgssonp.mongodb.net/
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRE=30d
      - SESSION_SECRET=your_session_secret_for_english_center_app
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=2wqZ5nlVaRLrXls86Q4BCqTXovd_3NvmoeVvMprStewkCiUC3
    command: "http app:3000"
    ports:
      - "4040:4040"
    depends_on:
      - app

volumes:
  uploads: